var packetLoss = 'Yes',
rebuffering = 'Yes',
Width = 1920, // videoWidth
Height = 1080, //videoHeight
videoPLC = 'freezing',
ARL = 1.3, //rebufferingLength in seconds
NRE = 1, //numRebufferingEvents
MREEF = 5, // rebufferingFactor
V_NBR = 1, // numVideos or Variable Number of Buffering Events Rate
videoContentCoding = 4,
codingCompression = 5,
MeasureTime = 300, //
V_Burst = 0.3, //ipPacketLoss in seconds (noramlly less than 1)
V_LossRate = 0.9, //ipPacketLossRate (less than 1)
GopLength = 12, //gopLength
V_BR = 8000, // videoBitrate
videoFrameRate = 30,
FrameRate = videoFrameRate,
TotalFrameNum = MeasureTime*videoFrameRate; 